# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/ComputerExperiment/project0_student/project0/project0_build/project0_build.cache/wt [current_project]
set_property parent.project_path E:/ComputerExperiment/project0_student/project0/project0_build/project0_build.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/ComputerExperiment/project0_student/project0/project0_build/project0_build.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/ComputerExperiment/project0_student/project0/origin/led.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/ComputerExperiment/project0_student/project0/origin/constr.xdc
set_property used_in_implementation false [get_files E:/ComputerExperiment/project0_student/project0/origin/constr.xdc]


synth_design -top led_pipe -part xc7z020clg484-1


write_checkpoint -force -noxdef led_pipe.dcp

catch { report_utilization -file led_pipe_utilization_synth.rpt -pb led_pipe_utilization_synth.pb }
